
## Server
server:
  service:
    type: NodePort
    nodePortHttps: 30002

## Mac m1 에서는 Argocd UI에서 github.com 도메인을 찾지 못해서 직접 IP를 넣어줬습니다.
global:
  hostAliases:
  - ip: 20.200.245.247
    hostnames:
    - github.com